[platformio]
default_envs =
    ble-uart-control-link
    xbox-controller-parser-demo

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.2
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:ble-uart-control-link]
board = esp32-c3-devkitc-02
build_flags =
    ${env.build_flags}
    -D DEMO_BLE_UART_CONTROL_LINK
    -D UART_RX_PIN=1
    -D UART_TX_PIN=0
    -D STATUS_LED_PIN=8

[env:xbox-controller-parser-demo]
board = esp32-c3-devkitm-1
build_flags =
    ${env.build_flags}
    -D DEMO_XBOX_CONTROLLER_PARSER
